const MINUTE = 60000;
module.exports = {
  MINUTE,
  TIMEOUT_DEPLOY: 1 * MINUTE,
  TIMEOUT_COMPUTE: 1 * MINUTE,
  TIMEOUT_COMPUTE_LONG: 2 * MINUTE,
  TIMEOUT_FAILDEPLOY: 1 * MINUTE,
  RETRIES_DEPLOY: 3,
  RETRIES_COMPUTE: 3
};
