name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Find $BRANCH_NAME
        run: echo "::set-env name=BRANCH_NAME::$(echo "$GITHUB_REF" | grep -o '[^/]\+$')"
      - name: Find $MATCHING_BRANCH_DOCKER
        run: echo "::set-env name=MATCHING_BRANCH_DOCKER::$(git ls-remote --heads https://github.com/enigmampc/docker-environment.git "$BRANCH_NAME" | wc -l)"
      - name: Git Clone
        run: |
          if [[ "$MATCHING_BRANCH_DOCKER" -eq 1 ]]; then
            # which includes master and develop because these always exist
            git clone --single-branch --branch "$BRANCH_NAME" https://github.com/enigmampc/docker-environment.git
          else
            # otherwise we are on a feature branch, and we'll build against develop
            git clone --single-branch --branch develop https://github.com/enigmampc/docker-environment.git
          fi
      - name: Build Docker Images
        working-directory: ./docker-environment
        run: |
          cp .env.template .env
          if [[ "$BRANCH_NAME" == "master" ]]; then
            DOCKER_TAG=latest
            make clone-contract BRANCH=master
          else
            DOCKER_TAG=develop
            make clone-contract BRANCH=develop
          fi
          sed -i "s/DOCKER_TAG=latest/DOCKER_TAG=${DOCKER_TAG}/" .env;
          docker pull "enigmampc/worker_sw:${DOCKER_TAG}"
          docker pull "enigmampc/key_management_sw:${DOCKER_TAG}"
          docker pull "enigmampc/contract:${DOCKER_TAG}"
          make clone-client-solo BRANCH="${BRANCH_NAME}"
          make build-client DOCKER_TAG="${DOCKER_TAG}"
      - name: Start Network
        working-directory: ./docker-environment
        run: docker-compose up -d
      - name: Wait for network to be ready
        working-directory: ./docker-environment
        run: |
          until ./is_ready.sh; do
            sleep 1
          done
      - name: Test
        working-directory: ./docker-environment
        run: docker-compose exec -T client make test
